import { test } from "node:test";
import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { hash, verify } from "@node-rs/argon2";
import { allowedActor, canAccess, canAssign, canTransition, type Actor } from "../lib/policy";
import { validatedFile, MAX_FILE_BYTES } from "../lib/files";
import { registerSchema, completeProfileSchema, passwordSchema } from "../lib/validation";
import { generateKeyPair, SignJWT } from "jose";
import { verifyGoogleToken } from "../lib/google-token";
const requester: Actor = { id: "owner", role: "USER", active: true };
const professional: Actor = { id: "professional", role: "PROFESSIONAL", active: true, professionalProfile: { enabled: true } };
const admin: Actor = { id: "admin", role: "ADMIN", active: true };
const ticket = { requesterId: "owner", assignedProfessionalId: "professional" };
test("requesters cannot access other people's cases", ()=>{ assert.ok(canAccess(requester,ticket)); assert.ok(!canAccess({...requester,id:"other"},ticket)); });
test("professionals only access their assigned cases",()=>{ assert.ok(canAccess(professional,ticket)); assert.ok(!canAccess({...professional,id:"other"},ticket)); assert.ok(!canAccess(professional,{...ticket,assignedProfessionalId:null})); });
test("disabled accounts and disabled professionals have no access",()=>{ assert.ok(!allowedActor({...admin,active:false})); assert.ok(!canAccess({...professional,professionalProfile:{enabled:false}},ticket)); assert.ok(!canAccess({...requester,active:false},ticket)); });
test("only ASTREA assigns after review and acceptance",()=>{ assert.ok(!canAssign("USER","IN_PROGRESS")); assert.ok(!canAssign("PROFESSIONAL","IN_PROGRESS")); assert.ok(!canAssign("ADMIN","NEW")); assert.ok(!canAssign("ADMIN","UNDER_REVIEW")); assert.ok(canAssign("ADMIN","IN_PROGRESS")); });
test("mandatory workflow cannot be skipped",()=>{ assert.ok(!canTransition("ADMIN","NEW","RESOLVED")); assert.ok(!canTransition("ADMIN","NEW","IN_PROGRESS")); assert.ok(canTransition("ADMIN","NEW","UNDER_REVIEW")); assert.ok(canTransition("ADMIN","UNDER_REVIEW","IN_PROGRESS")); assert.ok(canTransition("ADMIN","RESOLVED","CLOSED")); });
test("professionals cannot accept, assign, close or reopen cases",()=>{ assert.ok(!canTransition("PROFESSIONAL","UNDER_REVIEW","IN_PROGRESS")); assert.ok(!canTransition("PROFESSIONAL","RESOLVED","CLOSED")); assert.ok(!canTransition("PROFESSIONAL","CLOSED","UNDER_REVIEW")); assert.ok(canTransition("PROFESSIONAL","IN_PROGRESS","RESOLVED")); });
test("requesters cannot change status",()=>{ for(const from of ["NEW","UNDER_REVIEW","IN_PROGRESS"]) for(const to of ["UNDER_REVIEW","IN_PROGRESS","RESOLVED"]) assert.ok(!canTransition("USER",from,to)); });
test("file content, extension and MIME must agree",()=>{ assert.equal(validatedFile("report.pdf","application/pdf",Buffer.from("%PDF-1.7 test")),"report.pdf"); assert.throws(()=>validatedFile("report.pdf","application/pdf",Buffer.from("<script>"))); assert.throws(()=>validatedFile("report.exe","application/pdf",Buffer.from("%PDF-1.7"))); assert.throws(()=>validatedFile("report.pdf","image/png",Buffer.from("%PDF-1.7"))); });
test("uploads reject empty and oversized files, sanitize filenames",()=>{ assert.throws(()=>validatedFile("x.pdf","application/pdf",Buffer.alloc(0))); assert.throws(()=>validatedFile("x.pdf","application/pdf",Buffer.alloc(MAX_FILE_BYTES+1))); assert.equal(validatedFile("a/b.pdf","application/pdf",Buffer.from("%PDF-1.7")),"a_b.pdf"); });
test("registration requires consents and business identity",()=>{ const v={accountType:"CITIZEN",firstName:"Ada",lastName:"Test",email:"ada@example.invalid",password:randomBytes(24).toString("hex"),privacy:"on",terms:"on"}; assert.ok(registerSchema.safeParse(v).success); assert.ok(!registerSchema.safeParse({...v,privacy:undefined}).success); assert.ok(!registerSchema.safeParse({...v,accountType:"PROFESSIONAL"}).success); assert.ok(!registerSchema.safeParse({...v,accountType:"BUSINESS"}).success); assert.ok(registerSchema.safeParse({...v,accountType:"BUSINESS",companyName:"Test",vatNumber:"12345678901"}).success); assert.ok(!completeProfileSchema.safeParse({...v,accountType:"BUSINESS"}).success); });
test("passwords use salted Argon2 and reject weak inputs",async()=>{ assert.ok(!passwordSchema.safeParse("short").success); const password=randomBytes(24).toString("hex"); const a=await hash(password,{memoryCost:19456,timeCost:2,parallelism:1}); const b=await hash(password,{memoryCost:19456,timeCost:2,parallelism:1}); assert.ok(a!==b); assert.ok(a.startsWith("$argon2id$")); assert.ok(await verify(a,password)); assert.ok(!await verify(a,randomBytes(24).toString("hex"))); });
test("Google tokens reject bad signature, issuer, audience, nonce and expiry", async()=>{
  const key = await generateKeyPair("RS256"); const wrongKey = await generateKeyPair("RS256"); const nonce = randomBytes(24).toString("hex");
  const sign = (issuer="https://accounts.google.com", audience="test-client", expires="5m")=>new SignJWT({nonce}).setProtectedHeader({alg:"RS256"}).setSubject("test-user").setIssuer(issuer).setAudience(audience).setIssuedAt().setExpirationTime(expires).sign(key.privateKey);
  const valid = await sign(); const resolve = async()=>key.publicKey;
  assert.equal((await verifyGoogleToken(valid,resolve,"test-client",nonce)).sub,"test-user");
  await assert.rejects(()=>verifyGoogleToken(valid,async()=>wrongKey.publicKey,"test-client",nonce));
  await assert.rejects(()=>verifyGoogleToken(valid,resolve,"different-client",nonce));
  await assert.rejects(()=>verifyGoogleToken(valid,resolve,"test-client","different-nonce"));
  const invalidIssuer = await sign("https://foreign.invalid");
  await assert.rejects(()=>verifyGoogleToken(invalidIssuer,resolve,"test-client",nonce));
  const expired = await sign("https://accounts.google.com","test-client","-1s");
  await assert.rejects(()=>verifyGoogleToken(expired,resolve,"test-client",nonce));
});
