import PageFrame from "@/components/PageFrame";
export const metadata = { title: "Privacy", description: "Informazioni sul trattamento dei dati nello Sportello ASTREA." };
export default function Page() { return <PageFrame title="Privacy dello Sportello"><div className="panel max-w-4xl space-y-8">
  <section><h2 className="font-serif text-2xl">Chi tratta i dati</h2><p className="mt-3 leading-7">ASTREA, Associazione per lo Sviluppo del Territorio, la Ricerca, l&apos;Energia e l&apos;Ambiente, gestisce lo Sportello. {process.env.CONTACT_EMAIL ? `Per informazioni sul trattamento dei dati: ${process.env.CONTACT_EMAIL}.` : "I recapiti del titolare devono essere confermati da ASTREA prima dell'apertura pubblica del servizio."}</p></section>
  <section><h2 className="font-serif text-2xl">Dati e finalità</h2><p className="mt-3 leading-7">Il portale raccoglie dati anagrafici e di contatto, dati aziendali per le imprese, credenziali protette, contenuti delle pratiche, comunicazioni e documenti. Questi dati consentono di gestire l&apos;account, valutare le richieste, fornire riscontri e proteggere il servizio. Il telefono è facoltativo. Evita di inserire informazioni sensibili non necessarie alla tua richiesta.</p></section>
  <section><h2 className="font-serif text-2xl">Accesso e fornitori</h2><p className="mt-3 leading-7">Le pratiche sono accessibili al richiedente, agli amministratori ASTREA e al professionista eventualmente assegnato. Le note interne non sono visibili al richiedente. Il servizio utilizza fornitori per hosting, database, posta elettronica e storage privato. Se scegli Google, il portale riceve l&apos;identificativo Google, il nome e l&apos;email verificata; non conserva i token di accesso Google.</p></section>
  <section><h2 className="font-serif text-2xl">Conservazione e cookie</h2><p className="mt-3 leading-7">La sessione di accesso dura al massimo sette giorni ed è revocata all&apos;uscita o alla reimpostazione della password. I collegamenti email scadono dopo un&apos;ora. I cookie OAuth durano dieci minuti. Il portale non integra strumenti di tracciamento pubblicitario. I tempi di conservazione delle pratiche e dei documenti, le basi giuridiche e gli eventuali trasferimenti devono essere definiti dall&apos;associazione nella versione finale dell&apos;informativa.</p></section>
  <section><h2 className="font-serif text-2xl">I tuoi diritti</h2><p className="mt-3 leading-7">Puoi chiedere accesso, rettifica, cancellazione o limitazione dei tuoi dati e, quando applicabili, esercitare opposizione e portabilità. Puoi presentare reclamo all&apos;autorità di controllo. La presa visione dell&apos;informativa è registrata separatamente dall&apos;accettazione dei termini.</p></section>
  <p className="rounded-lg border border-astrea-line p-4 text-sm">Testo predisposto per la revisione di ASTREA: completare dati del titolare, basi giuridiche, conservazione e fornitori prima dell&apos;attivazione pubblica.</p>
  </div></PageFrame>; }
