import { notFound } from "next/navigation";
import PageFrame from "./PageFrame";
import PortalForm from "./PortalForm";
import { Select, Textarea } from "./Fields";
import { requireUser, area } from "@/lib/auth";
import { ticketDetail } from "@/lib/tickets";
import { db } from "@/lib/db";
import { canAssign, canTransition, type Actor } from "@/lib/policy";
import { statuses, priorities, categories, events, date } from "@/lib/labels";
import { storageConfigured } from "@/lib/storage";
export default async function TicketDetail({ role, id }: { role: Actor["role"]; id: string }) {
  const user = await requireUser(role); const ticket = await ticketDetail(user,id); if (!ticket) notFound();
  const professionals = role === "ADMIN" ? await db().user.findMany({ where: { role: "PROFESSIONAL", active: true, professionalProfile: { enabled: true } }, select: { id: true, firstName: true, lastName: true } }) : [];
  const options = Object.fromEntries(Object.entries(statuses).filter(([key])=>canTransition(role,ticket.status,key)));
  const hidden = <input type="hidden" name="ticketId" value={ticket.id} />;
  const professional = ticket.assignedProfessional;
  return <PageFrame title={ticket.subject} description={`${ticket.code} · ${categories[ticket.category]}`} parent={{ href: `${area(role)}/pratiche`, label: "Pratiche" }}>
    <div className="grid gap-8 lg:grid-cols-[1fr_330px]"><div className="space-y-8">
      <section className="panel"><span className="badge">{statuses[ticket.status]}</span><h2 className="mt-6 font-serif text-2xl">La richiesta</h2><p className="mt-4 whitespace-pre-wrap leading-7 break-words">{ticket.description}</p><p className="mt-6 text-sm">Inviata il {date(ticket.createdAt)}</p><p className="mt-3">Professionista: {professional ? `${professional.firstName || ""} ${professional.lastName || ""} · ${professional.professionalProfile?.profession || ""}` : "La pratica è coordinata da ASTREA. Nessun professionista assegnato."}</p>{role !== "USER" && <p className="mt-3">Richiedente: {ticket.requester.businessProfile?.companyName || `${ticket.requester.firstName || ""} ${ticket.requester.lastName || ""}`} · {ticket.requester.email}</p>}</section>
      <section className="panel"><h2 className="font-serif text-2xl">Comunicazioni</h2><div className="my-6 space-y-5">{ticket.messages.map(m=><article className={`rounded-lg border p-5 ${m.internalOnly ? "border-amber-300 bg-amber-50" : "border-astrea-line"}`} key={m.id}><p className="text-sm font-semibold">{m.internalOnly ? "Nota interna · " : ""}{m.author.firstName || ""} {m.author.lastName || ""} · {m.author.role === "ADMIN" ? "ASTREA" : m.author.role === "PROFESSIONAL" ? "Professionista" : "Richiedente"}</p><p className="mt-2 whitespace-pre-wrap break-words leading-7">{m.body}</p><p className="mt-3 text-xs">{date(m.createdAt)}</p></article>)}{!ticket.messages.length && <p>Non ci sono ancora comunicazioni.</p>}</div>{ticket.status !== "CLOSED" && <PortalForm endpoint="/api/portal/message" submit="Invia comunicazione">{hidden}<Textarea name="body" label="Messaggio" />{role !== "USER" && <label className="flex items-center gap-3"><input type="checkbox" name="internalOnly" />Nota interna, visibile solo ad ASTREA e al professionista assegnato</label>}</PortalForm>}</section>
      <section className="panel"><h2 className="font-serif text-2xl">Documenti</h2><ul className="my-6 space-y-3">{ticket.attachments.map(a=><li key={a.id}><a href={`/api/allegati/${a.id}`} className="underline break-words">{a.originalName}</a><span className="ml-3 text-sm">{(a.sizeBytes/1024).toFixed(0)} KB</span></li>)}</ul>{ticket.status !== "CLOSED" && (storageConfigured() ? <PortalForm endpoint="/api/portal/upload" submit="Carica documento">{hidden}<label className="field"><span>PDF, JPEG o PNG · massimo 10 MB</span><input type="file" name="file" accept="application/pdf,image/jpeg,image/png" required /></label></PortalForm> : <p>Il caricamento documenti non è ancora disponibile.</p>)}</section>
    </div><aside className="space-y-6">
      {role === "ADMIN" && ticket.assignedProfessionalId && !canAssign(role,ticket.status) && <section className="panel"><h2 className="mb-5 font-serif text-2xl">Assegnazione</h2><PortalForm endpoint="/api/portal/assign" submit="Rimuovi professionista">{hidden}<input type="hidden" name="professionalId" value="" /><p className="text-sm">Puoi rimuovere l&apos;assegnazione. Una nuova assegnazione richiede la presa in carico.</p></PortalForm></section>}
      {role !== "USER" && <section className="panel"><h2 className="mb-5 font-serif text-2xl">Gestione</h2>{Object.keys(options).length > 0 && <PortalForm endpoint="/api/portal/status" submit="Aggiorna stato">{hidden}<Select name="status" label="Passaggio successivo" options={options} /></PortalForm>}{role === "ADMIN" && <><div className="mt-6"><PortalForm endpoint="/api/portal/priority" submit="Aggiorna priorità">{hidden}<Select name="priority" label="Priorità" options={priorities} value={ticket.priority} /></PortalForm></div>{canAssign(role,ticket.status) && <div className="mt-6"><PortalForm endpoint="/api/portal/assign" submit="Aggiorna assegnazione">{hidden}<Select name="professionalId" label="Professionista" value={ticket.assignedProfessionalId || ""} options={Object.fromEntries(professionals.map(p=>[p.id,`${p.firstName || ""} ${p.lastName || ""}`]))} empty="Nessuna assegnazione" /></PortalForm></div>}</>}</section>}
      <section className="panel"><h2 className="font-serif text-2xl">Cronologia</h2><ol className="mt-6 space-y-6 border-l border-astrea-line pl-5">{ticket.events.map(e=><li key={e.id}><p className="font-semibold">{events[e.type]}{e.note === "internal" ? " (interna)" : ""}</p>{e.toValue && e.toValue in statuses && <p className="mt-1 text-sm">{e.fromValue && e.fromValue in statuses ? `${statuses[e.fromValue as keyof typeof statuses]} → ` : ""}{statuses[e.toValue as keyof typeof statuses]}</p>}{role === "ADMIN" && e.toValue && e.toValue in priorities && <p className="text-sm">{priorities[e.toValue as keyof typeof priorities]}</p>}{e.actor && <p className="mt-1 text-xs">{e.actor.firstName} {e.actor.lastName}{e.actor.role === "ADMIN" ? " · ASTREA" : ""}</p>}<time dateTime={e.createdAt.toISOString()} className="mt-2 block text-xs">{date(e.createdAt)}</time></li>)}</ol></section>
    </aside></div>
  </PageFrame>;
}
