export const publicContent: Record<string, { title: string; description: string; sections: { title: string; text: string }[]; links?: { label: string; href: string }[] }> = {
  "chi-siamo": { title: "Conoscenza al servizio del territorio", description: "ASTREA è l'Associazione per lo Sviluppo del Territorio, la Ricerca, l'Energia e l'Ambiente. Un'associazione culturale senza fini di lucro.", sections: [
    { title: "La nostra missione", text: "Mettere in relazione conoscenze scientifiche, competenze professionali e bisogni della comunità. Il territorio è il punto di partenza di un confronto aperto su ambiente, energia, ricerca e innovazione." },
    { title: "Un approccio multidisciplinare", text: "Le sfide dello sviluppo richiedono prospettive diverse. ASTREA promuove informazione, collaborazione e progettualità, favorendo il dialogo tra cittadini, imprese, professionisti e istituzioni." },
    { title: "Lo Sportello Tecnologico", text: "Un punto di accesso digitale per presentare esigenze e richieste di orientamento. ASTREA riceve le pratiche, le valuta e ne coordina la gestione, individuando le competenze appropriate." }], links: [{ label: "Scopri lo Sportello", href: "/sportello-tecnologico" }, { label: "La rete scientifica", href: "/rete-scientifica" }] },
  "rete-scientifica": { title: "Una rete di competenze", description: "Ricerca, esperienza professionale e confronto interdisciplinare per comprendere e affrontare le esigenze del territorio.", sections: [
    { title: "Le aree di conoscenza", text: "Ambiente e territorio, transizione energetica, tecnologie innovative, progettazione, sviluppo locale e conservazione del patrimonio costituiscono gli ambiti di riferimento della rete ASTREA." },
    { title: "Il coordinamento di ASTREA", text: "Le richieste allo Sportello vengono esaminate dall'associazione. L'eventuale coinvolgimento di un professionista avviene dopo la valutazione e la presa in carico, sotto il coordinamento di ASTREA." },
    { title: "Partecipare alla rete", text: "I professionisti non si registrano autonomamente allo Sportello. ASTREA crea e abilita gli account della propria rete. Per proporre una collaborazione, utilizza i canali di contatto dell'associazione." }], links: [{ label: "Contatta ASTREA", href: "/contatti" }] },
  "attivita": { title: "Le attività di ASTREA", description: "Informazione, ricerca e iniziative per uno sviluppo consapevole e sostenibile.", sections: [
    { title: "Territorio e ambiente", text: "Confronto sui bisogni delle comunità, tutela del paesaggio e valorizzazione delle risorse locali. Un approccio che collega conoscenza del territorio e responsabilità ambientale." },
    { title: "Energia e tecnologie", text: "Approfondimento della transizione energetica, dell'efficienza e degli strumenti digitali. Le competenze della rete aiutano a inquadrare le esigenze di cittadini e imprese." },
    { title: "Ricerca e partecipazione", text: "Scambio di conoscenze e idee tra soci, ricercatori, professionisti e comunità. Le proposte sono un punto di partenza per costruire occasioni di confronto e collaborazione." }], links: [{ label: "Proposte di ASTREA", href: "/proposte-di-astrea" }, { label: "Attività dei soci", href: "/attivita-dei-soci" }] },
  "proposte-di-astrea": { title: "Proposte di ASTREA", description: "Uno spazio per i temi e i percorsi di lavoro dell'associazione.", sections: [
    { title: "Conoscere prima di progettare", text: "Raccogliere bisogni, mettere a confronto le competenze e definire l'ambito delle richieste: lo Sportello Tecnologico rende questo percorso accessibile e tracciabile." },
    { title: "Dalle esigenze alle collaborazioni", text: "Ambiente, energia, ricerca e sviluppo locale sono i temi attorno ai quali costruire un dialogo tra persone e organizzazioni. Le iniziative approvate saranno pubblicate in questa sezione." }], links: [{ label: "Presenta un'esigenza", href: "/sportello-tecnologico" }] },
  "le-mie-proposte": { title: "Le tue proposte", description: "Condividi un'idea o un'esigenza legata agli ambiti di ASTREA.", sections: [
    { title: "Come presentare una proposta", text: "Registrati come cittadino o impresa e apri una pratica dalla tua area personale. Indica la categoria, un oggetto chiaro e una descrizione con obiettivi, contesto e bisogni. Dopo l'invio puoi aggiungere documenti." },
    { title: "Un confronto che puoi seguire", text: "ASTREA valuta la proposta e comunica attraverso la pratica. Dalla tua area puoi leggere i messaggi, rispondere e consultare la cronologia degli aggiornamenti." }], links: [{ label: "Apri una proposta", href: "/area-riservata/pratiche/nuova" }, { label: "Le tue pratiche", href: "/area-riservata/pratiche" }] },
  "attivita-dei-soci": { title: "Attività dei soci", description: "Conoscenze e contributi che alimentano la vita dell'associazione.", sections: [
    { title: "Condividere esperienze", text: "Le competenze dei soci sono una risorsa per il confronto sui temi del territorio, della ricerca, dell'energia e dell'ambiente. Questa sezione raccoglierà le attività e i contributi approvati dall'associazione." },
    { title: "Proporre un contributo", text: "Per segnalare un'attività, una ricerca o una proposta di collaborazione, contatta ASTREA. Le informazioni pubblicate devono essere confermate dall'associazione prima della diffusione." }], links: [{ label: "Contatti", href: "/contatti" }, { label: "Presenta una proposta", href: "/le-mie-proposte" }] },
  "notizie": { title: "Notizie e approfondimenti", description: "Uno spazio editoriale dedicato ad ambiente, tecnologia ed energie rinnovabili.", sections: [{ title: "La conoscenza come punto di partenza", text: "Gli articoli saranno pubblicati dopo la revisione di ASTREA. Al momento non sono presenti notizie pubblicate: esplora gli ambiti editoriali qui sotto." }], links: [{ label: "Ambiente", href: "/notizie/ambiente" }, { label: "Tecnologia", href: "/notizie/technologia" }, { label: "Energie rinnovabili", href: "/notizie/energie-rinnovabili" }] },
  "notizie/ambiente": { title: "Ambiente", description: "Territorio, biodiversità, paesaggio e sostenibilità.", sections: [{ title: "Approfondimenti ambientali", text: "Questa sezione è dedicata al rapporto tra comunità e ambiente, alla tutela delle risorse e alla conoscenza del territorio. Non sono ancora presenti articoli pubblicati." }], links: [{ label: "Tutte le notizie", href: "/notizie" }, { label: "Attività di ASTREA", href: "/attivita" }] },
  "notizie/technologia": { title: "Tecnologia", description: "Innovazione, strumenti digitali e nuove opportunità per il territorio.", sections: [{ title: "Capire l'innovazione", text: "Tecnologie e competenze digitali possono aiutare a leggere le esigenze di persone e imprese. Questa sezione ospiterà approfondimenti verificati da ASTREA. Non sono ancora presenti articoli pubblicati." }], links: [{ label: "Tutte le notizie", href: "/notizie" }, { label: "Sportello Tecnologico", href: "/sportello-tecnologico" }] },
  "notizie/energie-rinnovabili": { title: "Energie rinnovabili", description: "Transizione energetica, efficienza e fonti rinnovabili.", sections: [{ title: "Energia e comunità", text: "Questa sezione raccoglierà contenuti sulla sostenibilità energetica e sul ruolo dell'innovazione nello sviluppo locale. Non sono ancora presenti articoli pubblicati." }], links: [{ label: "Tutte le notizie", href: "/notizie" }, { label: "Presenta una richiesta", href: "/sportello-tecnologico" }] },
};
